name: stream_final
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1