name: calculator_modularization_presentation_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.3.0
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  provider: 6.1.1

  calculator_modularization_presentation:
    path: presentation
  calculator_modularization_data:
    path: data
  calculator_modularization_domain:
    path: domain

dev_dependencies:
  flutter_lints: 3.0.1